#!/usr/bin/env python3
"""Generate a JS file listing all fields in the PDF form.

Reads: prototypes/orchestrator/data/form_fields_pdf_extracted.txt
Writes: prototypes/orchestrator/js/pdf-fields.js
"""

from pathlib import Path

inp = Path("prototypes/orchestrator/data/form_fields_pdf_extracted.txt")
out = Path("prototypes/orchestrator/js/pdf-fields.js")

if not inp.exists():
    raise SystemExit(f"Input file not found: {inp}")

import re

fields = []
current_page = 0

for line in inp.read_text(encoding="utf-8").splitlines():
    line = line.rstrip("\n")
    if not line.strip():
        continue
    if line.startswith("Page "):
        # "Page 1:" or "Page (unknown):"
        header = line[len("Page "):].strip()
        if header.startswith("(unknown"):
            current_page = 0
        else:
            try:
                current_page = int(header.rstrip(":"))
            except Exception:
                current_page = 0
        continue

    # Expect lines like:   'Foo  ' (Text)
    m = re.match(r"\s*(['\"])(.*)\1\s+\(([^)]+)\)", line)
    if not m:
        # fallback: take everything before the last '(' as name
        if "(" in line:
            name = line.rsplit("(", 1)[0].strip()
            field_type = line.rsplit("(", 1)[1].rstrip(")").strip()
        else:
            name = line.strip()
            field_type = "Unknown"
    else:
        name = m.group(2)
        field_type = m.group(3)

    fields.append({"name": name, "type": field_type, "page": current_page})

# Build a dictionary of fields, keeping first seen entry if there are duplicates.
field_map = {}
for f in fields:
    if f["name"] not in field_map:
        field_map[f["name"]] = {"type": f["type"], "page": f["page"]}

# Output JS
out.write_text(
    """// Auto-generated list of PDF form fields.
// Generated by scripts/generate_pdf_fields_js.py

export const PDF_FIELDS = {
""" +
    ",\n".join(
        f"    {repr(name)}: {{type: {repr(info['type'])}, page: {info['page']}}}"
        for name, info in field_map.items()
    ) +
    "\n};\n\nexport const PDF_FIELD_NAMES = new Set(Object.keys(PDF_FIELDS));\n",
    encoding="utf-8",
)

print(f"Wrote {out} ({len(field_map)} field names)")
